const FETCH_FAVORITES_START = 'FETCH_FAVORITES_START',
      UPDATE_FAVORITES = 'UPDATE_FAVORITES',
      FETCH_FAVORITES_ERROR = 'FETCH_FAVORITES_ERROR',
      UPDATE_AMOUNT = 'UPDATE_AMOUNT',
      REMOVE_TRACK = 'REMOVE_TRACK',
      SHUFFLE_TRACKS = 'SHUFFLE_TRACKS';

module.exports = {
  FETCH_FAVORITES_START,
  UPDATE_FAVORITES,
  FETCH_FAVORITES_ERROR,
  UPDATE_AMOUNT,
  REMOVE_TRACK,
  SHUFFLE_TRACKS
};