const TOGGLE_TRACK = 'TOGGLE_TRACK',
      CHANGE_CURRENT_TIME = 'CHANGE_CURRENT_TIME',
      CHANGE_PLAYING_TRACK = 'CHANGE_PLAYING_TRACK',
      NEXT_TRACK = 'NEXT_TRACK',
      PREV_TRACK = 'PREV_TRACK',
      TOGGLE_REPEAT_TRACK = 'TOGGLE_REPEAT_TRACK';

module.exports = {
  TOGGLE_TRACK,
  CHANGE_CURRENT_TIME,
  CHANGE_PLAYING_TRACK,
  NEXT_TRACK,
  PREV_TRACK,
  TOGGLE_REPEAT_TRACK
};