const FETCH_PLAYLIST_START = 'FETCH_PLAYLIST_START',
      UPDATE_PLAYLIST = 'UPDATE_PLAYLIST',
      FETCH_PLAYLIST_ERROR = 'FETCH_PLAYLIST_ERROR',
      UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT',
      SHUFFLE_TRACKS = 'SHUFFLE_TRACKS',
      CONCAT_PARTIAL_TRACKS = 'CONCAT_PARTIAL_TRACKS';

module.exports = {
  FETCH_PLAYLIST_START,
  UPDATE_PLAYLIST,
  FETCH_PLAYLIST_ERROR,
  UPDATE_SEARCH_TEXT,
  SHUFFLE_TRACKS,
  CONCAT_PARTIAL_TRACKS
};